version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
      java: corretto17
    commands:
      - echo "Installing NPM dependencies..."
      - npm install
      - echo "Downloading OWASP Dependency-Check..."
      - curl -sLO https://github.com/jeremylong/DependencyCheck/releases/download/v9.0.9/dependency-check-9.0.9-release.zip
      - echo "Unzipping Dependency-Check..."
      - unzip dependency-check-9.0.9-release.zip
  pre_build:
    commands:
      - echo "Pre-build phase"
  build:
    commands:
      - echo "Build phase: Running OWASP Dependency-Check analysis..."
      # Cria o diret칩rio para os relat칩rios
      - mkdir -p reports
      # Atualiza o PATH para incluir a pasta do Dependency-Check
      - export PATH=$PATH:$(pwd)/dependency-check/bin
      # Executa a an치lise; ajuste "meu-projeto" conforme necess치rio
      - dependency-check.sh --project "meu-projeto" --scan . --format HTML --out reports/
  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Uploading Dependency-Check reports to S3..."
      # Substitua 'meu-bucket-de-relatorios' pelo nome do seu bucket S3
      - aws s3 cp reports/ s3://meu-bucket-de-relatorios/ --recursive

artifacts:
  files:
    - '**/*'
