version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Baixando OWASP Dependency-Check..."
      - wget https://github.com/jeremylong/DependencyCheck/releases/download/v7.4.0/dependency-check-7.4.0-release.zip
      - unzip dependency-check-7.4.0-release.zip
      - rm dependency-check-7.4.0-release.zip
      - chmod +x dependency-check/bin/dependency-check.sh
      - echo "Dependency-Check baixado e configurado."
  build:
    commands:
      - echo "Iniciando análise de dependências..."
      - dependency-check/bin/dependency-check.sh --project "MeuProjeto" --format HTML --out dependency-check-report --scan .
      - echo "Análise concluída. Relatórios em ./dependency-check-report"
  post_build:
    commands:
      - echo "Pipeline concluído com sucesso."
artifacts:
  files:
    - '**/*'
  base-directory: 'dependency-check-report'
  discard-paths: no
